export const IPC_CHANNELS = {
  listProjects: "studio:list-projects",
  listFlows: "studio:list-flows",
  getFlow: "studio:get-flow",
  importFlowFile: "studio:import-flow-file",
  exportFlowFile: "studio:export-flow-file",
  getFlowRunInput: "studio:get-flow-run-input",
  renameFlow: "studio:rename-flow",
  runFlow: "studio:run-flow",
  cancelExecution: "studio:cancel-execution",
  executionProgress: "studio:execution-progress",
  getExecution: "studio:get-execution",
  createProject: "studio:create-project",
  listExecutions: "studio:list-executions",
  deleteExecution: "studio:delete-execution",
  listFlowVersions: "studio:list-flow-versions",
  getFlowVersion: "studio:get-flow-version",
  restoreFlowVersion: "studio:restore-flow-version",
  openPath: "studio:open-path",
} as const;
